ArmCartesianControl:
  active: true
  priority: 3
  gains: 2.0
  trajectories:
    arm1:
      - type: poly5
      - points:
          - [0.15708, -0.5831, 0.8, 3.14, 0, 0]
        T: 15
    arm2:
      - type: poly5
      - points:
          - [0.50, 0.05, 0.10, -3.14, 0.0, 0.0]
        T: 15