# Default initial positions for srm's ros2_control fake system

initial_positions:
  left_base_joint: 0
  right_base_joint: 0
  ur_left_elbow_joint: 0
  ur_left_shoulder_lift_joint: 0
  ur_left_shoulder_pan_joint: 0
  ur_left_wrist_1_joint: 0
  ur_left_wrist_2_joint: 0
  ur_left_wrist_3_joint: 0
  ur_right_elbow_joint: 0
  ur_right_shoulder_lift_joint: 0
  ur_right_shoulder_pan_joint: 0
  ur_right_wrist_1_joint: 0
  ur_right_wrist_2_joint: 0
  ur_right_wrist_3_joint: 0