# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - srm_r_ur_controller
    - multi_dof_joint_trajectory_action_right
    - multi_dof_joint_trajectory_action_left
    - srm_l_ur_controller

  srm_r_ur_controller:
    type: FollowJointTrajectory
    joints:
      - ur_right_shoulder_pan_joint
      - ur_right_shoulder_lift_joint
      - ur_right_elbow_joint
      - ur_right_wrist_1_joint
      - ur_right_wrist_2_joint
      - ur_right_wrist_3_joint

  srm_l_ur_controller:
    type: FollowJointTrajectory
    joints:
      - ur_left_shoulder_pan_joint
      - ur_left_shoulder_lift_joint
      - ur_left_elbow_joint
      - ur_left_wrist_1_joint
      - ur_left_wrist_2_joint
      - ur_left_wrist_3_joint
      
  multi_dof_joint_trajectory_action_left:
    type: MultiDofFollowJointTrajectory
    action_ns: multi_dof_joint_trajectory_action
    joints:
      - left_base_joint

  multi_dof_joint_trajectory_action_right:
    type: MultiDofFollowJointTrajectory
    action_ns: multi_dof_joint_trajectory_action
    joints:
      - right_base_joint