# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - srm_r_base_controller
    - srm_r_ur_controller
    - srm_l_base_controller
    - srm_l_ur_controller

  srm_r_base_controller:
    type: FollowJointTrajectory
    joints:
      - right_summit_back_left_wheel_joint
      - right_summit_back_right_wheel_joint
      - right_summit_front_left_wheel_joint
      - right_summit_front_right_wheel_joint
  srm_r_ur_controller:
    type: FollowJointTrajectory
    joints:
      - ur_right_shoulder_pan_joint
      - ur_right_shoulder_lift_joint
      - ur_right_elbow_joint
      - ur_right_wrist_1_joint
      - ur_right_wrist_2_joint
      - ur_right_wrist_3_joint
  srm_l_base_controller:
    type: FollowJointTrajectory
    joints:
      - left_summit_back_left_wheel_joint
      - left_summit_back_right_wheel_joint
      - left_summit_front_left_wheel_joint
      - left_summit_front_right_wheel_joint
  srm_l_ur_controller:
    type: FollowJointTrajectory
    joints:
      - ur_left_shoulder_pan_joint
      - ur_left_shoulder_lift_joint
      - ur_left_elbow_joint
      - ur_left_wrist_1_joint
      - ur_left_wrist_2_joint
      - ur_left_wrist_3_joint